from rebound_db import get_rebound_sim_coplanar
from resonantstate.data_download  import get_metadata_observations, download_observations_samples
from resonantstate.constants import *
import celmech as cm
from celmech.lie_transformations import FirstOrderGeneratingFunction
from matplotlib import pyplot as plt
from argparse import ArgumentParser
import numpy as np
import sympy as sp
import pandas as pd
from celmech.poincare import _get_a0_symbol,_get_Lambda0_symbol
from pathlib import Path
from celmech.disturbing_function import list_resonance_terms


def create_mass_dependent_osc_to_mean_function(chi):
    """
    Construct a mass-dependent transformation from osculating to mean
    Poincare canonical variables.

    Uses a first-order Lie transformation generated by `chi` to compute
    mean canonical variables from osculating variables:

        X_mean = X_osc - {X_osc, chi}

    where {.,.} denotes the Poisson bracket.

    The transformation is constructed symbolically and then compiled
    into a numerical function using SymPy's `lambdify`. Planet masses
    are retained as explicit arguments, allowing the same transformation
    to be evaluated for different planet masses without recomputing
    the generating function.

    In particular, the mass dependence of the reference actions
    Lambda_{i,0} is made explicit using

        Lambda_{i,0} = m_i * sqrt(G * M_i * a_{i,0}),

    where m_i is the planet mass, M_i is the corresponding central
    mass parameter, and a_{i,0} is the reference semimajor axis.

    The reduced masses mu_i are approximated by the planet masses m_i.
    All remaining Hamiltonian parameters are replaced by their values
    stored in `chi.H_params`.

    Parameters
    ----------
    chi : celmech.lie_transformations.FirstOrderGeneratingFunction
        First-order Lie generating function defining the canonical
        transformation. Its canonical variables, Hamiltonian parameters,
        and reference actions determine the symbolic transformation.

    Returns
    -------
    osc_to_mean_function : callable
        Numerical function mapping osculating to mean canonical variables.
        Accepts positional arguments consisting of the canonical variables
        in `chi.qp_vars`, followed by the planet masses in order.

        Returns an array of transformed canonical variables in the same
        order as `chi.qp_vars`, with shape (len(chi.qp_vars), 1).

    Notes
    -----
    The transformation is accurate to first order in the generating
    function. Higher-order Lie derivatives are neglected.

    The generating function and its derivatives are evaluated using
    the orbital configuration and Hamiltonian parameters used to
    construct `chi`. Only the explicit mass dependence retained in
    the symbolic transformation is varied between evaluations.
    """
    nb_planets = chi.N - 1
    params = chi.H_params.copy()
    G = sp.symbols("G")
    Ms = sp.symbols(f"M(1:{nb_planets+1})")
    ms = sp.symbols(f"m(1:{nb_planets+1})")
    mus = sp.symbols(f"mu(1:{nb_planets+1})")

    # we'll approximate each occurence of mu_i by m_i, as they are nearly identical
    mu_to_m = dict(zip(mus,ms))

    # The values of the parameters Lambda_{i,0} implicitly depend on planet masses.
    # We'll make this dependence explicit
    Lambda0_rule=dict()
    for i,m in enumerate(ms):
        Lambda0_rule[_get_Lambda0_symbol(i+1)] = m*sp.sqrt(G*Ms[i] * _get_a0_symbol(i+1))

    # remove mass parameters from params dictionary
    for m,mu in zip(ms,mus):
        params.pop(m)
        params.pop(mu)

    osc_to_mean_exprn = sp.Matrix([v - chi.Lie_deriv(v).xreplace(Lambda0_rule).xreplace(params).xreplace(mu_to_m) for v in chi.qp_vars])

    osc_to_mean_function = sp.lambdify(chi.qp_vars + list(ms), osc_to_mean_exprn, **chi._lambdify_kwargs)
    return osc_to_mean_function

def get_posterior_data(system_name,id_num=0):
    """
    Get posterior samples for specified system.
    """
    dataframe_observations = get_metadata_observations()
    df_selected = dataframe_observations[dataframe_observations["star_name"].isin([system_name])]
    df_list = download_observations_samples(df_selected)
    samples_dict = df_list[id_num]
    print(f"Selected samples from {samples_dict['author_name']} using a '{samples_dict['mass_prior']}' prior on mass and '{samples_dict['eccentricity_prior']}' prior on eccentricities")
    samples_df = samples_dict['samples']
    nb_planets = samples_dict['nb_planets']
    return nb_planets,samples_df,{k:samples_dict[k] for k in ('author_name','mass_prior','eccentricity_prior')}


def make_generating_function(pvars, dj_max=4):
    """
    Construct a first-order Lie generating function for transforming
    between osculating and mean Poincare variables.

    For each adjacent planet pair, the generating function includes
    zeroth-order (in eccentricity) terms and first-order mean-motion
    resonance (MMR) terms, excluding the first-order resonance nearest
    to the pair's observed period ratio.

    Specifically, for a pair nearest to the j:(j-1) MMR, the
    generating function includes terms associated with the
    k:(k-1) resonances, where k = j + dj and
    1 <= |dj| <= dj_max.

    The nearest resonance (dj = 0) is deliberately excluded so that
    its resonant dynamics are retained in the averaged Hamiltonian,
    rather than eliminated by the canonical transformation.

    Parameters
    ----------
    pvars : celmech.Poincare
        Poincare canonical variables specifying the planetary system.
        The orbital periods determine the nearest first-order MMR
        for each adjacent planet pair.
    dj_max : int, optional
        Maximum integer offset from the nearest first-order MMR
        included in the generating function. Default is 4.

    Returns
    -------
    chi : celmech.lie_transformations.FirstOrderGeneratingFunction
        First-order generating function defining the near-identity
        canonical transformation between osculating and mean variables.

    Notes
    -----
    Only interactions between adjacent planets are included.
    Resonant terms are restricted to first order in eccentricity
    (max_order=1, l_max=1).

    The function prints the nearest first-order MMR identified for
    each adjacent planet pair.
    """
    chi = FirstOrderGeneratingFunction(pvars)
    nb_planets = chi.N-1
    dj_vals = np.concatenate((-1*np.arange(1,dj_max+1),np.arange(1,dj_max+1)))
    for i in range(1,nb_planets):    
        chi.add_zeroth_order_term(indexIn=i,indexOut=i+1)
        nearest_first_order = int(np.round(1/(1 - chi.particles[i].P/chi.particles[i+1].P)))
        print(f"Planet {i} and {i+1} near {nearest_first_order}:{nearest_first_order-1}")

        # No dj = 0: Since we want to capture the dynamics with the SFMR, 
        #we should not eliminate the resonant terms that form part of the model.
        for dj in dj_vals:
            ## Note to self:
            ## Not using 'add_MMR_terms' because it doesn't support
            ## negative k values-- update at some point!
            # chi.add_MMR_terms(k,1,max_order=1,indexIn=i,indexOut=i+1,l_max = 1)
            k = nearest_first_order+dj
            terms = list_resonance_terms(k,1)
            for k,_ in list_resonance_terms(k,1):
                chi.add_cosine_term(k,max_order=1,l_max=1,indexIn=i,indexOut=i+1)
            
    return chi
def parse_args():
    p = ArgumentParser(
        description="Convert posterior data from mean to osculating elements"
    )
    p.add_argument(
        "--system",
        default="Kepler-60",
        help="System for which posterior data is to be converted"
    )
    p.add_argument(
        "--author_id",
        default=0,
        type=int,
        help="Specify which author/prior combination as an integer."
    )
    p.add_argument(
        "--dj_max",
        default=4,
        type=int,
        help="Osculating corrections from k:k-1 first-order MMRs for 1<= |k-j| <= dj_max will be included for pairs near j:j-1 MMRs"
    )
    p.add_argument(
        "--file_name",
        default=None,
        type=str,
        help="Name of file to which mean element posterior data will be saved."
    )
    p.add_argument(
        "--save_dir",
        default="./",
        type=str,
        help="Name of file to which mean element posterior data will be saved."
    )

    return p.parse_args()

def osc_to_mean(pvars,osc_to_mean_function):
    new_vals = osc_to_mean_function(*pvars.values,*[p.m for p in pvars.particles[1:]]).reshape(-1)
    pvars.values = new_vals

def main():
    args = parse_args()
    save_path = Path(args.save_dir)
    nb_planets,samples_df,info = get_posterior_data(args.system,id_num = args.author_id)
    ## modify to use posterior medians when making generating function?
    # posterior_medians = {c:samples_df[c].median() for c in samples_df.columns} 

    # Construct a representative system using median posterior values
    median_df = samples_df.median(numeric_only=True).to_frame().T
    median_df.index = [0]

    sim0 = get_rebound_sim_coplanar(
        median_df,
        range(nb_planets),
        0
    )
    pvars = cm.Poincare.from_Simulation(sim0)
    chi = make_generating_function(pvars)
    osc_to_mean_func = create_mass_dependent_osc_to_mean_function(chi)

    rad2deg = 180 / np.pi
    new_rows = []

    for sample_id, row in samples_df.iterrows():
        sim = get_rebound_sim_coplanar(
            samples_df,
            range(nb_planets),
            sample_id
        )

        pvars = cm.Poincare.from_Simulation(sim)
        osc_to_mean(pvars,osc_to_mean_func)
        sim_mean = pvars.to_Simulation()

        orbits = sim_mean.orbits(primary=sim_mean.particles[0])
        mstar = sim_mean.particles[0].m

        # Convert the original row to a mutable dictionary.
        new_row = row.to_dict()

        for planet_id, orbit in enumerate(orbits):
            new_row.update({
                f"mean_longitude_deg_{planet_id}": orbit.l * rad2deg,
                f"period_days_{planet_id}": orbit.P * 365.25,
                f"k_{planet_id}": orbit.pal_k,
                f"h_{planet_id}": orbit.pal_h,
                f"mass_planet_star_ratio_{planet_id}":
                    sim_mean.particles[planet_id + 1].m / mstar,
            })

        new_rows.append(new_row)

    df_mean = pd.DataFrame(new_rows, index=samples_df.index)
    if args.file_name is None:
        save_file=f"./{args.system}_author_{info['author_name']}"
        save_file+=f"_ecc_prior_{info['eccentricity_prior']}_mass_prior_{info['mass_prior']}_mean_posteriors.pkl"
        save_file= save_path / save_file
    else:
        save_file = save_path/args.file_name
    df_mean.to_pickle(save_file)

if __name__=="__main__":
    main()